Search.appendIndex(
    [
                {
            "fqsen": "\\splitbrain\\slika\\Adapter",
            "name": "Adapter",
            "summary": "Base\u0020class\u0020for\u0020image\u0020adapters.\u0020Defines\u0020what\u0020image\u0020processing\u0020adapters\u0020need\u0020to\u0020provide",
            "url": "classes/splitbrain-slika-Adapter.html"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "New\u0020Slika\u0020Adapter",
            "url": "classes/splitbrain-slika-Adapter.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003Aautorotate\u0028\u0029",
            "name": "autorotate",
            "summary": "Rote\u0020the\u0020image\u0020based\u0020on\u0020the\u0020rotation\u0020exif\u0020tag",
            "url": "classes/splitbrain-slika-Adapter.html#method_autorotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003Arotate\u0028\u0029",
            "name": "rotate",
            "summary": "Rotate\u0020and\/or\u0020flip\u0020the\u0020image",
            "url": "classes/splitbrain-slika-Adapter.html#method_rotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "Resize\u0020to\u0020make\u0020image\u0020fit\u0020the\u0020given\u0020dimension\u0020\u0028maintaining\u0020the\u0020aspect\u0020ratio\u0029",
            "url": "classes/splitbrain-slika-Adapter.html#method_resize"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003Acrop\u0028\u0029",
            "name": "crop",
            "summary": "Resize\u0020to\u0020the\u0020given\u0020dimension,\u0020cropping\u0020the\u0020image\u0020as\u0020needed",
            "url": "classes/splitbrain-slika-Adapter.html#method_crop"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Save\u0020the\u0020new\u0020file",
            "url": "classes/splitbrain-slika-Adapter.html#method_save"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003A\u0024imagepath",
            "name": "imagepath",
            "summary": "",
            "url": "classes/splitbrain-slika-Adapter.html#property_imagepath"
        },                {
            "fqsen": "\\splitbrain\\slika\\Adapter\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/splitbrain-slika-Adapter.html#property_options"
        },                {
            "fqsen": "\\splitbrain\\slika\\Exception",
            "name": "Exception",
            "summary": "Exception\u0020thrown\u0020on\u0020all\u0020errors\u0020during\u0020image\u0020processing",
            "url": "classes/splitbrain-slika-Exception.html"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter",
            "name": "GdAdapter",
            "summary": "Image\u0020processing\u0020adapter\u0020for\u0020PHP\u0027s\u0020libGD",
            "url": "classes/splitbrain-slika-GdAdapter.html"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "New\u0020Slika\u0020Adapter",
            "url": "classes/splitbrain-slika-GdAdapter.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Clean\u0020up",
            "url": "classes/splitbrain-slika-GdAdapter.html#method___destruct"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003Aautorotate\u0028\u0029",
            "name": "autorotate",
            "summary": "Rote\u0020the\u0020image\u0020based\u0020on\u0020the\u0020rotation\u0020exif\u0020tag",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_autorotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003Arotate\u0028\u0029",
            "name": "rotate",
            "summary": "Rotate\u0020and\/or\u0020flip\u0020the\u0020image",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_rotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "Resize\u0020to\u0020make\u0020image\u0020fit\u0020the\u0020given\u0020dimension\u0020\u0028maintaining\u0020the\u0020aspect\u0020ratio\u0029",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_resize"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003Acrop\u0028\u0029",
            "name": "crop",
            "summary": "Resize\u0020to\u0020the\u0020given\u0020dimension,\u0020cropping\u0020the\u0020image\u0020as\u0020needed",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_crop"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Save\u0020the\u0020new\u0020file",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_save"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003AloadImage\u0028\u0029",
            "name": "loadImage",
            "summary": "Initialize\u0020libGD\u0020on\u0020the\u0020given\u0020image",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_loadImage"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003AcreateImage\u0028\u0029",
            "name": "createImage",
            "summary": "Creates\u0020a\u0020new\u0020blank\u0020image\u0020to\u0020which\u0020we\u0020can\u0020copy",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_createImage"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003AkeepGifTransparency\u0028\u0029",
            "name": "keepGifTransparency",
            "summary": "Copy\u0020transparency\u0020from\u0020gif\u0020to\u0020gif",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_keepGifTransparency"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003AcropPosition\u0028\u0029",
            "name": "cropPosition",
            "summary": "Calculates\u0020crop\u0020position",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_cropPosition"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003AresizeOperation\u0028\u0029",
            "name": "resizeOperation",
            "summary": "resize\u0020or\u0020crop\u0020images\u0020using\u0020PHP\u0027s\u0020libGD\u0020support",
            "url": "classes/splitbrain-slika-GdAdapter.html#method_resizeOperation"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003A\u0024image",
            "name": "image",
            "summary": "",
            "url": "classes/splitbrain-slika-GdAdapter.html#property_image"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/splitbrain-slika-GdAdapter.html#property_width"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/splitbrain-slika-GdAdapter.html#property_height"
        },                {
            "fqsen": "\\splitbrain\\slika\\GdAdapter\u003A\u003A\u0024extension",
            "name": "extension",
            "summary": "",
            "url": "classes/splitbrain-slika-GdAdapter.html#property_extension"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo",
            "name": "ImageInfo",
            "summary": "Lightweight,\u0020metadata\u002Donly\u0020inspection\u0020of\u0020an\u0020image.",
            "url": "classes/splitbrain-slika-ImageInfo.html"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AgetRawWidth\u0028\u0029",
            "name": "getRawWidth",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_getRawWidth"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AgetRawHeight\u0028\u0029",
            "name": "getRawHeight",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_getRawHeight"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AgetExtension\u0028\u0029",
            "name": "getExtension",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_getExtension"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AgetOrientation\u0028\u0029",
            "name": "getOrientation",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_getOrientation"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_getWidth"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AgetHeight\u0028\u0029",
            "name": "getHeight",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_getHeight"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AgetDimensions\u0028\u0029",
            "name": "getDimensions",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_getDimensions"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003Aautorotate\u0028\u0029",
            "name": "autorotate",
            "summary": "Simulate\u0020Adapter\u003A\u003Aautorotate\u0028\u0029\u0020at\u0020the\u0020dimension\u0020level.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_autorotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003Arotate\u0028\u0029",
            "name": "rotate",
            "summary": "Simulate\u0020Adapter\u003A\u003Arotate\u0028\u0029\u0020at\u0020the\u0020dimension\u0020level.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_rotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "Simulate\u0020Adapter\u003A\u003Aresize\u0028\u0029\u0020at\u0020the\u0020dimension\u0020level.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_resize"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003Acrop\u0028\u0029",
            "name": "crop",
            "summary": "Simulate\u0020Adapter\u003A\u003Acrop\u0028\u0029\u0020at\u0020the\u0020dimension\u0020level.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_crop"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AreadExifOrientation\u0028\u0029",
            "name": "readExifOrientation",
            "summary": "Read\u0020the\u0020EXIF\u0020orientation\u0020tag\u0020of\u0020a\u0020JPEG\u0020file.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_readExifOrientation"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AreadExifOrientationFromBytes\u0028\u0029",
            "name": "readExifOrientationFromBytes",
            "summary": "Raw\u002Dbyte\u0020fallback\u0020for\u0020reading\u0020the\u0020EXIF\u0020orientation\u0020tag.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_readExifOrientationFromBytes"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AboundingBox\u0028\u0029",
            "name": "boundingBox",
            "summary": "Calculate\u0020new\u0020size\u0020to\u0020fit\u0020into\u0020a\u0020bounding\u0020box,\u0020preserving\u0020aspect\u0020ratio.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_boundingBox"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003AcleanDimension\u0028\u0029",
            "name": "cleanDimension",
            "summary": "Normalize\u0020a\u0020dimension\u0020value\u0020to\u0020a\u0020pixel\u0020count.",
            "url": "classes/splitbrain-slika-ImageInfo.html#method_cleanDimension"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A\u0024imagepath",
            "name": "imagepath",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#property_imagepath"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A\u0024rawWidth",
            "name": "rawWidth",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#property_rawWidth"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A\u0024rawHeight",
            "name": "rawHeight",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#property_rawHeight"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A\u0024extension",
            "name": "extension",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#property_extension"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A\u0024orientation",
            "name": "orientation",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#property_orientation"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#property_width"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageInfo\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageInfo.html#property_height"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter",
            "name": "ImageMagickAdapter",
            "summary": "Image\u0020Processing\u0020Adapter\u0020for\u0020ImageMagick\u0027s\u0020command\u0020line\u0020utility\u0020\u0060convert\u0060",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "New\u0020Slika\u0020Adapter",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter\u003A\u003Aautorotate\u0028\u0029",
            "name": "autorotate",
            "summary": "Rote\u0020the\u0020image\u0020based\u0020on\u0020the\u0020rotation\u0020exif\u0020tag",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html#method_autorotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter\u003A\u003Arotate\u0028\u0029",
            "name": "rotate",
            "summary": "Rotate\u0020and\/or\u0020flip\u0020the\u0020image",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html#method_rotate"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "Resize\u0020to\u0020make\u0020image\u0020fit\u0020the\u0020given\u0020dimension\u0020\u0028maintaining\u0020the\u0020aspect\u0020ratio\u0029",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html#method_resize"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter\u003A\u003Acrop\u0028\u0029",
            "name": "crop",
            "summary": "Resize\u0020to\u0020the\u0020given\u0020dimension,\u0020cropping\u0020the\u0020image\u0020as\u0020needed",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html#method_crop"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Save\u0020the\u0020new\u0020file",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html#method_save"
        },                {
            "fqsen": "\\splitbrain\\slika\\ImageMagickAdapter\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/splitbrain-slika-ImageMagickAdapter.html#property_args"
        },                {
            "fqsen": "\\splitbrain\\slika\\Slika",
            "name": "Slika",
            "summary": "Factory\u0020to\u0020process\u0020an\u0020image\u0020using\u0020an\u0020available\u0020Adapter",
            "url": "classes/splitbrain-slika-Slika.html"
        },                {
            "fqsen": "\\splitbrain\\slika\\Slika\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Start\u0020processing\u0020the\u0020image",
            "url": "classes/splitbrain-slika-Slika.html#method_run"
        },                {
            "fqsen": "\\splitbrain\\slika\\Slika\u003A\u003AROTATE_CCW",
            "name": "ROTATE_CCW",
            "summary": "rotate\u0020an\u0020image\u0020counter\u0020clock\u0020wise",
            "url": "classes/splitbrain-slika-Slika.html#constant_ROTATE_CCW"
        },                {
            "fqsen": "\\splitbrain\\slika\\Slika\u003A\u003AROTATE_CW",
            "name": "ROTATE_CW",
            "summary": "rotate\u0020an\u0020image\u0020clock\u0020wise",
            "url": "classes/splitbrain-slika-Slika.html#constant_ROTATE_CW"
        },                {
            "fqsen": "\\splitbrain\\slika\\Slika\u003A\u003AROTATE_TOPDOWN",
            "name": "ROTATE_TOPDOWN",
            "summary": "rotate\u0020on\u0020it\u0027s\u0020head",
            "url": "classes/splitbrain-slika-Slika.html#constant_ROTATE_TOPDOWN"
        },                {
            "fqsen": "\\splitbrain\\slika\\Slika\u003A\u003ADEFAULT_OPTIONS",
            "name": "DEFAULT_OPTIONS",
            "summary": "these\u0020can\u0020be\u0020overwritten\u0020using\u0020the\u0020options\u0020array\u0020in\u0020run\u0028\u0029",
            "url": "classes/splitbrain-slika-Slika.html#constant_DEFAULT_OPTIONS"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\splitbrain\\slika",
            "name": "slika",
            "summary": "",
            "url": "namespaces/splitbrain-slika.html"
        },                {
            "fqsen": "\\splitbrain",
            "name": "splitbrain",
            "summary": "",
            "url": "namespaces/splitbrain.html"
        }            ]
);
